name: PHP App Monitoring

on:
  # Run this action every 5 minutes
  schedule:
    - cron: "*/1 * * * *"  # This cron expression will run the script every 1 minutes
  # Optionally, you can also trigger manually
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Run PHP App Monitor Script
      run: |
        chmod +x phpappmonitor.sh
        ./phpappmonitor.sh
