name: PHP App Monitoring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated from v2 to v3 for Node.js 20 support

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run PHP App Monitoring Script
        run: |
          chmod +x phpappmonitor.sh
          ./phpappmonitor.sh
